---
apiVersion: "route.openshift.io/v1"
kind: "Route"
metadata:
  labels:
    expose: "true"
    app: "openapi-car-api"
    provider: "fabric8"
    version: "1.0-SNAPSHOT"
    group: "io.example"
  name: "openapi-car-api"
spec:
  port:
    targetPort: 8080
  to:
    kind: "Service"
    name: "openapi-car-api"
